### ISSUE TITLE
Vertical booking form translation

### ISSUE THREAD

**Issue by vivianairis** [hqrentalsoftware/wordpress-hq#29]
### Ticket
https://caagsoftware.zendesk.com/agent/tickets/61294

### Description
The home page vertical form is not translate to english or spanish. The default should stay in Portuguese but when clients are translating the website in spanish or english the full website translate except the form.

Miguel added a script to avoid this when using the Google translation plugin, but needs to update due to recent updates

**Comment by diegoseso** [comment]
#31
