### ISSUE TITLE
Update CNAME Records

### ISSUE THREAD

**Issue by vivianairis** [hqrentalsoftware/wordpress-hq#57]
### Description
Please update CNAME records:

- [ ] RV Rental Platinum

Please update the CNAME record to continue with the website integration process.
https://www.whatsmydns.net/#CNAME/platinum-rv-rental.platinumrvrental.com
https://caagsoftware.zendesk.com/agent/tickets/63869

**Comment by FaggioniHQ** [comment]
Hello @vivianairis ,

I added the CNAME
